spring:
  application:
    name: api
  config:
    import: optional:file:.env[.properties]

  # MySQL
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform: all

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_APPNAME}.b2pc5.mongodb.net/?retryWrites=true&w=majority&appName=${MONGODB_APPNAME}
      database: ${MONGODB_SCHEMA}
server:
  port: 8080

eda:
  kafka:
    bootstrap-server: j12s004.p.ssafy.io:8003
    consumer-group: consumer-java





