spring:
  application:
    name: api
    version: v1
  config:
    import: optional:file:.env[.properties]

  # MySQL
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  #  sql:
  #    init:
  #      data-locations: classpath*:db/data.sql
  #      mode: always
  #      platform: all

  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_URL}/${MONGODB_DATABASE}?authSource=admin

server:
  port: 8080

eda:
  kafka:
    bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER}
    consumer-group: ${KAFKA_CONSUMER_GROUP}

springdoc:
  swagger-ui:
    path: /api-swagger
    groups-order: DESC
    operations-sorter: method
  paths-to-match:
    - /api/**

management:
  endpoints:
    web:
      exposure:
        include: prometheus

# Loki 로깅 설정
loki:
  url: ${LOKI_URL}
